# Generated by Django 4.1 on 2024-03-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confeccao', models.CharField(choices=[('Serrano', 'Serrano'), ('Vara', 'Vara')], max_length=7)),
                ('numero', models.CharField(max_length=25, unique=True)),
            ],
        ),
    ]
