# Generated by Django 4.1 on 2024-03-11 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0005_alter_estado_nome_alter_estado_uf_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='comarca',
            field=models.BooleanField(default=False, verbose_name='É comarca'),
        ),
        migrations.CreateModel(
            name='Vara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Vara')),
                ('tipo_vara', models.CharField(choices=[('Cível', 'Cível'), ('Única', 'Única'), ('Juizado', 'Juizado'), ('Criminal', 'Criminal'), ('Família', 'Família'), ('Fazenda Pública', 'Fazenda Pública'), ('Federal', 'Federal'), ('Trabalho', 'Trabalho'), ('Dívida Ativa', 'Dívida Ativa'), ('Juizado Especial Cível', 'Juizado Especial Cível'), ('Extrajudicial', 'Extrajudicial'), ('Mista', 'Mista')], max_length=50, verbose_name='Tipo de Vara')),
                ('juiz', models.CharField(max_length=255, verbose_name='Juiz')),
                ('juiz_substituto', models.CharField(blank=True, max_length=255, verbose_name='Juiz Substituto')),
                ('comarca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extracao_pdf.cidade', verbose_name='Comarca')),
            ],
        ),
    ]
