# Generated by Django 4.1 on 2024-03-11 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0006_alter_cidade_comarca_vara'),
    ]

    operations = [
        migrations.CreateModel(
            name='Executado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Exequente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TerceiroInteressado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='processo',
            name='executados',
            field=models.ManyToManyField(blank=True, to='extracao_pdf.executado'),
        ),
        migrations.AddField(
            model_name='processo',
            name='exequentes',
            field=models.ManyToManyField(blank=True, to='extracao_pdf.exequente'),
        ),
        migrations.AddField(
            model_name='processo',
            name='terceiros_interessados',
            field=models.ManyToManyField(blank=True, to='extracao_pdf.terceirointeressado'),
        ),
    ]
