# Generated by Django 4.1 on 2024-03-12 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0007_executado_exequente_terceirointeressado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='data_divida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='valor_divida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
