# Generated by Django 4.1 on 2024-03-13 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0010_processo_depositario_processo_onus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição do Bem')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor do Bem')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bens', to='extracao_pdf.processo')),
            ],
        ),
    ]
