# Generated by Django 4.1 on 2024-03-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0011_bem'),
    ]

    operations = [
        migrations.AddField(
            model_name='bem',
            name='data_avaliacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Avaliação'),
        ),
        migrations.AddField(
            model_name='bem',
            name='tipo_bem',
            field=models.CharField(choices=[('Automoveis', 'Automóveis'), ('Equipamentos', 'Equipamentos'), ('Imoveis', 'Imóveis'), ('Semoventes', 'Semoventes')], default='Imoveis', max_length=20, verbose_name='Tipo do Bem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bem',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Avaliação'),
        ),
    ]
