# Generated by Django 4.1 on 2024-03-22 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0013_matricula_leiloeiro_processo_leiloeiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='processos_pdfs/'),
        ),
    ]
