# Generated by Django 4.1 on 2024-03-29 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0016_remove_justica_esfera_justica_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vara',
            name='tipo_vara',
        ),
        migrations.AddField(
            model_name='vara',
            name='justica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='extracao_pdf.justica', verbose_name='Justiça'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='justica',
            name='tipo',
            field=models.CharField(choices=[('justica_eleitoral', 'Justiça Eleitoral'), ('justica_estadual', 'Justiça Estadual'), ('justica_federal', 'Justiça Federal'), ('justica_trabalho', 'Justiça do Trabalho')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vara',
            name='juiz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Juiz'),
        ),
    ]
