# Generated by Django 4.1 on 2024-03-29 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0017_remove_vara_tipo_vara_vara_justica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='vara',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extracao_pdf.vara', verbose_name='Vara'),
        ),
    ]
