# Generated by Django 4.1 on 2024-04-01 20:04

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0018_processo_vara'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
            ],
        ),
        migrations.AddField(
            model_name='processo',
            name='conteudo_texto_rico',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
