# Generated by Django 4.1 on 2024-04-02 03:01

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0019_mymodel_processo_conteudo_texto_rico'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='leiloeiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='extracao_pdf.leiloeiro'),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='nome_modelo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='tipo_arquivo',
            field=models.CharField(blank=True, choices=[('sugestao_datas', 'Sugestão de Datas')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Modelo'),
        ),
    ]
