# Generated by Django 4.1 on 2024-04-02 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0020_mymodel_leiloeiro_mymodel_nome_modelo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='modelo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extracao_pdf.mymodel', verbose_name='Modelo de Documento'),
        ),
    ]
