# Generated by Django 4.1 on 2024-04-02 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0021_processo_modelo_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='conteudo_texto_rico',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='modelo_documento',
        ),
    ]
