# Generated by Django 4.1 on 2024-04-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0023_alter_matricula_bairro_alter_matricula_cep_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leiloeiro',
            name='site',
        ),
        migrations.AlterField(
            model_name='leiloeiro',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='leiloeiro',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
    ]
