# Generated by Django 4.1 on 2024-04-22 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0025_leiloeiro_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leilao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('judicial', 'Leilão Judicial'), ('extrajudicial', 'Leilão Extrajudicial'), ('particular', 'Alienação Particular'), ('venda_direta', 'Venda Direta')], max_length=50)),
                ('modalidade', models.CharField(choices=[('eletronico', 'Eletrônico'), ('presencial', 'Presencial'), ('misto', 'Misto')], max_length=50)),
                ('local_realizacao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataLeilao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotulo', models.CharField(max_length=255)),
                ('data_hora', models.DateTimeField()),
                ('leilao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='extracao_pdf.leilao')),
            ],
        ),
    ]
