# Generated by Django 4.1 on 2024-04-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0026_leilao_dataleilao'),
    ]

    operations = [
        migrations.AddField(
            model_name='leilao',
            name='processos',
            field=models.ManyToManyField(blank=True, related_name='leiloes', to='extracao_pdf.processo', verbose_name='Processos Associados'),
        ),
    ]
