# Generated by Django 4.1 on 2024-04-22 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0027_leilao_processos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataleilao',
            name='leilao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas_leilao', to='extracao_pdf.leilao'),
        ),
    ]
