# Generated by Django 4.1 on 2024-04-22 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0028_alter_dataleilao_leilao'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='leilao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_vinculados', to='extracao_pdf.leilao', verbose_name='Leilão'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='processos_pdfs/', verbose_name='Arquivo PDF'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='classe_processual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extracao_pdf.classeprocessual', verbose_name='Classe Processual'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='data_divida',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Dívida'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='executados',
            field=models.ManyToManyField(blank=True, to='extracao_pdf.executado', verbose_name='Executados'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='exequentes',
            field=models.ManyToManyField(blank=True, to='extracao_pdf.exequente', verbose_name='Exequentes'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='terceiros_interessados',
            field=models.ManyToManyField(blank=True, to='extracao_pdf.terceirointeressado', verbose_name='Terceiros Interessados'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='valor_divida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da Dívida'),
        ),
    ]
