# Generated by Django 4.1 on 2024-04-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0029_processo_leilao_alter_processo_arquivo_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leilao',
            name='local_realizacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leilao',
            name='modalidade',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='leilao',
            name='processos',
            field=models.ManyToManyField(blank=True, related_name='leiloes', to='extracao_pdf.processo', verbose_name='Processos'),
        ),
        migrations.AlterField(
            model_name='leilao',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
    ]
