# Generated by Django 4.1 on 2024-04-24 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0030_alter_leilao_local_realizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leilao',
            name='modalidade',
            field=models.CharField(choices=[('eletronico', 'Eletrônico'), ('presencial', 'Presencial'), ('misto', 'Misto')], max_length=50),
        ),
        migrations.AlterField(
            model_name='leilao',
            name='tipo',
            field=models.CharField(choices=[('judicial', 'Leilão Judicial'), ('extrajudicial', 'Leilão Extrajudicial'), ('particular', 'Alienação Particular'), ('venda_direta', 'Venda Direta')], max_length=50),
        ),
    ]
