# Generated by Django 4.1 on 2024-04-24 03:09

from django.db import migrations, models
import extracao_pdf.validators


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0032_leiloeiro_timbrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='vara',
            name='timbrado',
            field=models.FileField(blank=True, null=True, upload_to='timbrados_varas/', validators=[extracao_pdf.validators.validate_file_extension], verbose_name='Timbrado (.docx)'),
        ),
    ]
