# Generated by Django 4.1 on 2024-04-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0033_vara_timbrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='timbrado_leiloeiro',
            field=models.BooleanField(default=False, verbose_name='Usa Timbrado do Leiloeiro'),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='timbrado_vara',
            field=models.BooleanField(default=False, verbose_name='Usa Timbrado da Vara'),
        ),
    ]
