# Generated by Django 4.1 on 2024-04-27 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0034_mymodel_timbrado_leiloeiro_mymodel_timbrado_vara'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='vara',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='extracao_pdf.vara'),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='timbrado_leiloeiro',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='timbrado_vara',
            field=models.BooleanField(default=False),
        ),
    ]
