# Generated by Django 4.1 on 2024-04-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0035_mymodel_vara_alter_mymodel_timbrado_leiloeiro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='timbrado_leiloeiro',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='timbrado_vara',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='timbrado',
            field=models.CharField(choices=[('none', 'Nenhum'), ('vara', 'Vara'), ('leiloeiro', 'Leiloeiro')], default='none', max_length=10),
        ),
    ]
