# Generated by Django 4.1 on 2024-05-06 17:18

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0036_remove_mymodel_timbrado_leiloeiro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='tipo_arquivo',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='e_modelo_padrao',
            field=models.BooleanField(default=False, help_text='Marcar como modelo padrão para o tipo de documento'),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='leiloeiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelos_leiloeiro', to='extracao_pdf.leiloeiro'),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='nome_modelo',
            field=models.CharField(default='Padrão', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='vara',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelos_vara', to='extracao_pdf.vara'),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='tipo_documento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='extracao_pdf.tipodocumento'),
        ),
    ]
