# Generated by Django 4.1 on 2024-05-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0038_alter_leilao_modalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataleilao',
            name='complemento',
            field=models.CharField(choices=[('às', 'às'), ('a partir das', 'a partir das')], default='às', max_length=12),
        ),
    ]
