# Generated by Django 4.1 on 2024-05-30 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0039_dataleilao_complemento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='leilao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_associados', to='extracao_pdf.leilao', verbose_name='Leilão Vinculado'),
        ),
    ]
