# Generated by Django 4.1 on 2024-05-30 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0040_alter_processo_leilao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='e_modelo_padrao',
        ),
        migrations.AlterField(
            model_name='matricula',
            name='numero',
            field=models.CharField(blank=True, max_length=10, verbose_name='Número'),
        ),
    ]
