# Generated by Django 4.1 on 2024-05-30 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0041_remove_mymodel_e_modelo_padrao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='arquivo_pdf',
        ),
        migrations.CreateModel(
            name='ProcessoArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='processos_arquivos/', verbose_name='Arquivo')),
                ('nome_arquivo', models.CharField(max_length=255, verbose_name='Nome do Arquivo')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='extracao_pdf.processo', verbose_name='Processo')),
            ],
        ),
    ]
