# Generated by Django 4.1 on 2024-06-05 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0042_remove_processo_arquivo_pdf_processoarquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='justica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelos_justica', to='extracao_pdf.justica'),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='timbrado',
            field=models.CharField(choices=[('none', 'Nenhum'), ('vara', 'Vara'), ('leiloeiro', 'Leiloeiro'), ('justica', 'Justiça')], default='none', max_length=10),
        ),
    ]
