# Generated by Django 4.1 on 2024-06-05 03:59

from django.db import migrations, models
import extracao_pdf.validators


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0043_mymodel_justica_alter_mymodel_timbrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='justica',
            name='timbrado',
            field=models.FileField(blank=True, null=True, upload_to='timbrados_justicas/', validators=[extracao_pdf.validators.validate_file_extension], verbose_name='Timbrado (.docx)'),
        ),
    ]
