# Generated by Django 4.1 on 2024-07-08 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0044_justica_timbrado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bem',
            options={'verbose_name_plural': 'Bens'},
        ),
        migrations.AddField(
            model_name='processo',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='confeccao',
            field=models.CharField(choices=[('Serrano', 'Serrano'), ('Vara', 'Vara')], max_length=7, verbose_name='Confecção'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='numero',
            field=models.CharField(max_length=25, unique=True, verbose_name='Número'),
        ),
    ]
