# Generated by Django 4.1 on 2024-07-29 02:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('extracao_pdf', '0046_board_card_status_processo_responsavel_list_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='mentions', to=settings.AUTH_USER_MODEL),
        ),
    ]
