# Generated by Django 4.1 on 2024-08-01 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0047_comment_mentions'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='lista_kanban',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelos', to='extracao_pdf.list'),
        ),
    ]
