# Generated by Django 4.1 on 2024-08-02 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0048_mymodel_lista_kanban'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={},
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='lista_kanban',
        ),
        migrations.AddField(
            model_name='list',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listas', to='extracao_pdf.tipodocumento'),
        ),
    ]
