# Generated by Django 4.1 on 2024-08-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0049_alter_list_options_remove_mymodel_lista_kanban_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='tipo_documento',
        ),
        migrations.AddField(
            model_name='list',
            name='modelos',
            field=models.ManyToManyField(blank=True, related_name='lists', to='extracao_pdf.mymodel'),
        ),
    ]
