# Generated by Django 4.1 on 2024-08-03 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0051_remove_list_modelos_list_tipos_documento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['ordem']},
        ),
        migrations.RemoveField(
            model_name='list',
            name='tipos_documento',
        ),
    ]
