# Generated by Django 4.1 on 2024-08-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0054_remove_gruporesponsavel_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='tipos_documento',
            field=models.ManyToManyField(related_name='listas', to='extracao_pdf.tipodocumento'),
        ),
    ]
