# Generated by Django 4.1 on 2024-08-09 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0056_remove_list_tipos_documento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processoarquivo',
            name='nome_arquivo',
        ),
        migrations.AddField(
            model_name='processoarquivo',
            name='nome_arquivo_customizado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Arquivo Customizado'),
        ),
        migrations.AddField(
            model_name='processoarquivo',
            name='tipo_documento',
            field=models.CharField(choices=[('EF', 'Edital Finalizado'), ('SD', 'Sugestão de Datas'), ('OT', 'Outro')], default='OT', max_length=2, verbose_name='Tipo de Documento'),
        ),
    ]
