# Generated by Django 4.1 on 2024-08-09 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0057_remove_processoarquivo_nome_arquivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='processoarquivo',
            name='nome_arquivo_customizado',
        ),
        migrations.RemoveField(
            model_name='processoarquivo',
            name='tipo_documento',
        ),
        migrations.AddField(
            model_name='processoarquivo',
            name='nome_arquivo',
            field=models.CharField(default='Arquivo Sem Nome', max_length=255, verbose_name='Nome do Arquivo'),
        ),
        migrations.AlterField(
            model_name='processoarquivo',
            name='arquivo',
            field=models.FileField(upload_to='processos_arquivos/', verbose_name='Arquivo'),
        ),
        migrations.AddField(
            model_name='processoarquivo',
            name='tipo_anexo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='extracao_pdf.tipoanexo', verbose_name='Tipo de Anexo'),
            preserve_default=False,
        ),
    ]
