# Generated by Django 4.1 on 2024-08-10 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0058_tipoanexo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processoarquivo',
            name='nome_arquivo',
            field=models.CharField(max_length=255, verbose_name='Nome do Arquivo'),
        ),
    ]
