# Generated by Django 4.1 on 2024-08-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0060_notificationrecipient_emailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='email_templates', to='extracao_pdf.notificationrecipient'),
        ),
    ]
