# Generated by Django 4.1 on 2024-08-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0063_notificationrecipient_alter_list_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='anexos',
            field=models.ManyToManyField(blank=True, related_name='email_templates', to='extracao_pdf.tipoanexo'),
        ),
    ]
