# Generated by Django 4.1 on 2024-08-21 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0067_logentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogEntry',
        ),
    ]
