# Generated by Django 4.1 on 2024-08-21 22:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0069_vara_bairro_vara_cep_vara_email_vara_endereco_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classeprocessual',
            options={'verbose_name': 'Classe processual', 'verbose_name_plural': 'Classes processuais'},
        ),
        migrations.AlterModelOptions(
            name='frasepadrao',
            options={'verbose_name': 'Frases Padrões', 'verbose_name_plural': 'Frases Padrões'},
        ),
        migrations.AddField(
            model_name='processo',
            name='preco_vil',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Preço Vil (%)'),
        ),
    ]
