# Generated by Django 4.1 on 2024-08-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0070_alter_classeprocessual_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='artigo_definido',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Artigo Definido'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Estado'),
        ),
    ]
