# Generated by Django 4.1 on 2024-08-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0071_estado_artigo_definido_alter_estado_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='matricula',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número da Matrícula'),
        ),
    ]
