# Generated by Django 4.1 on 2024-08-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0072_alter_matricula_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='leiloeiro',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1, verbose_name='Sexo'),
            preserve_default=False,
        ),
    ]
