# Generated by Django 4.1 on 2024-08-22 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0073_leiloeiro_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataleilao',
            name='tipo_data',
            field=models.CharField(choices=[('abertura', 'Abertura'), ('encerramento', 'Encerramento'), ('outro', 'Outro')], default='outro', max_length=12, verbose_name='Tipo de Data'),
        ),
    ]
