# Generated by Django 4.1 on 2024-08-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0074_dataleilao_tipo_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataleilao',
            name='rotulo',
        ),
        migrations.AddField(
            model_name='dataleilao',
            name='etapa',
            field=models.CharField(choices=[('primeiro', 'Primeiro Leilão'), ('segundo', 'Segundo Leilão'), ('terceiro', 'Terceiro Leilão'), ('quarto', 'Quarto Leilão'), ('quinto', 'Quinto Leilão'), ('sexto', 'Sexto Leilão')], default='primeiro', max_length=10, verbose_name='Etapa do Leilão'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dataleilao',
            name='tipo_data',
            field=models.CharField(choices=[('abertura', 'Abertura'), ('encerramento', 'Encerramento')], max_length=12, verbose_name='Tipo de Data'),
        ),
    ]
