# Generated by Django 4.1 on 2024-08-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0075_remove_dataleilao_rotulo_dataleilao_etapa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataleilao',
            name='etapa',
            field=models.CharField(choices=[('unico', 'Leilão único'), ('primeiro', 'Primeiro Leilão'), ('segundo', 'Segundo Leilão'), ('terceiro', 'Terceiro Leilão'), ('quarto', 'Quarto Leilão'), ('quinto', 'Quinto Leilão'), ('sexto', 'Sexto Leilão')], max_length=10, verbose_name='Etapa do Leilão'),
        ),
        migrations.AlterField(
            model_name='dataleilao',
            name='tipo_data',
            field=models.CharField(choices=[('abertura', 'Abertura'), ('encerramento', 'Encerramento'), ('inicio', 'Início')], max_length=12, verbose_name='Tipo de Data'),
        ),
    ]
