# Generated by Django 4.1 on 2024-08-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0076_alter_dataleilao_etapa_alter_dataleilao_tipo_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='executado',
            name='tipo_pessoa',
            field=models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2, verbose_name='Tipo de Pessoa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exequente',
            name='tipo_pessoa',
            field=models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2, verbose_name='Tipo de Pessoa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='terceirointeressado',
            name='tipo_pessoa',
            field=models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2, verbose_name='Tipo de Pessoa'),
            preserve_default=False,
        ),
    ]
