# Generated by Django 4.1 on 2024-08-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0077_executado_tipo_pessoa_exequente_tipo_pessoa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bem',
            name='localizacao',
            field=models.TextField(blank=True, verbose_name='Localização do Bem'),
        ),
    ]
