# Generated by Django 4.1 on 2024-08-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0078_bem_localizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='venda_direta',
            field=models.BooleanField(default=False, verbose_name='Venda Direta'),
        ),
    ]
