# Generated by Django 4.1 on 2024-08-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0080_alter_emaillog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leiloeiro',
            name='site',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
