# Generated by Django 4.1 on 2024-09-05 02:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0081_alter_leiloeiro_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='data_cadastro',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Cadastro'),
        ),
    ]
