# Generated by Django 4.1 on 2024-09-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0082_processo_data_cadastro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='processo',
        ),
        migrations.AddField(
            model_name='card',
            name='processos',
            field=models.ManyToManyField(blank=True, related_name='cards', to='extracao_pdf.processo'),
        ),
    ]
