# Generated by Django 4.1 on 2024-09-15 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0083_remove_card_processo_card_processos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='processos',
        ),
        migrations.AddField(
            model_name='card',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='extracao_pdf.processo'),
        ),
    ]
