# Generated by Django 4.1 on 2024-09-15 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0084_remove_card_processos_card_processo'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='leilao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards_leilao', to='extracao_pdf.leilao'),
        ),
        migrations.AddField(
            model_name='card',
            name='vara',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards_vara', to='extracao_pdf.vara'),
        ),
    ]
