# Generated by Django 4.1 on 2024-09-15 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0085_card_leilao_card_vara'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='leiloeiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards_leiloeiro', to='extracao_pdf.leiloeiro'),
        ),
    ]
