# Generated by Django 4.1 on 2024-09-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0086_card_leiloeiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_aggregated',
            field=models.BooleanField(default=False),
        ),
    ]
