# Generated by Django 4.1 on 2024-09-21 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0087_card_is_aggregated'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardsAgregados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agregacao', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards_agregados', to='extracao_pdf.card')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extracao_pdf.processo')),
            ],
        ),
    ]
