# Generated by Django 4.1 on 2024-10-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0088_cardsagregados'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='alto_valor',
            field=models.BooleanField(default=False, verbose_name='Alto Valor'),
        ),
    ]
