# Generated by Django 4.1 on 2024-10-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0089_card_alto_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bem',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Avaliação'),
        ),
    ]
