# Generated by Django 4.1 on 2024-10-08 17:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0092_alter_processo_leiloeiro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gruporesponsavel',
            options={'verbose_name': 'Grupos responsáveis', 'verbose_name_plural': 'Grupos responsáveis'},
        ),
        migrations.AlterModelOptions(
            name='justica',
            options={'verbose_name': 'Justiças', 'verbose_name_plural': 'Justiças'},
        ),
        migrations.AlterModelOptions(
            name='terceirointeressado',
            options={'verbose_name': 'Terceiros interessados', 'verbose_name_plural': 'Terceiros interessados'},
        ),
        migrations.CreateModel(
            name='PenhoraExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message='Número do processo deve estar no formato NNNNNNN-NN.NNNN.N.NN.NNNN', regex='^\\d{7}-\\d{2}\\.\\d{4}\\.\\d\\.\\d{2}\\.\\d{4}$')], verbose_name='Número do Processo')),
                ('exequente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extracao_pdf.exequente', verbose_name='Exequente')),
                ('processo_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penhoras_externas', to='extracao_pdf.processo')),
                ('vara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extracao_pdf.vara', verbose_name='Vara')),
            ],
            options={
                'verbose_name': 'Penhora Externa',
                'verbose_name_plural': 'Penhoras Externas',
            },
        ),
    ]
