# Generated by Django 4.1 on 2024-10-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0093_alter_gruporesponsavel_options_alter_justica_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='matricula',
            field=models.CharField(max_length=50, verbose_name='Número da Matrícula'),
        ),
    ]
