# Generated by Django 4.1 on 2024-10-19 03:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0095_processo_fls_divida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leilao',
            options={'verbose_name': 'Leilões', 'verbose_name_plural': 'Leilões'},
        ),
        migrations.AddField(
            model_name='dataleilao',
            name='data_abertura',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_data': 'abertura'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datas_vinculadas', to='extracao_pdf.dataleilao', verbose_name='Data de Abertura Vinculada'),
        ),
        migrations.AlterField(
            model_name='dataleilao',
            name='tipo_data',
            field=models.CharField(choices=[('encerramento', 'Encerramento'), ('inicio', 'Início')], max_length=12, verbose_name='Tipo de Data'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='fls_divida',
            field=models.PositiveIntegerField(blank=True, help_text='Número da página onde o valor da dívida foi encontrado', null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Fls. da Dívida'),
        ),
    ]
