# Generated by Django 4.1 on 2024-10-19 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0096_alter_leilao_options_dataleilao_data_abertura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataleilao',
            name='data_abertura',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abertura_para', to='extracao_pdf.dataleilao', verbose_name='Data de Abertura'),
        ),
    ]
