# Generated by Django 4.1 on 2024-10-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0097_alter_dataleilao_data_abertura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataleilao',
            name='data_abertura',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Abertura'),
        ),
        migrations.AlterField(
            model_name='dataleilao',
            name='data_hora',
            field=models.DateTimeField(verbose_name='Data e Hora'),
        ),
    ]
