# Generated by Django 4.1 on 2024-10-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0098_alter_dataleilao_data_abertura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataleilao',
            name='tem_abertura',
            field=models.BooleanField(default=False, verbose_name='Tem Data de Abertura?'),
        ),
    ]
