# Generated by Django 4.1 on 2024-10-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0099_dataleilao_tem_abertura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataleilao',
            name='tem_abertura',
        ),
        migrations.RemoveField(
            model_name='dataleilao',
            name='tipo_data',
        ),
        migrations.AlterField(
            model_name='dataleilao',
            name='data_hora',
            field=models.DateTimeField(verbose_name='Data e Hora do Leilão'),
        ),
    ]
