# Generated by Django 4.1 on 2024-10-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0101_dataleilao_tipo_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='publicado',
            field=models.BooleanField(default=False, verbose_name='Publicado'),
        ),
    ]
