# Generated by Django 4.1 on 2024-10-31 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0102_card_publicado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataleilao',
            options={'verbose_name': 'Data Leilões', 'verbose_name_plural': 'Data Leilões'},
        ),
        migrations.AddField(
            model_name='executado',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='exequente',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='terceirointeressado',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
    ]
