# Generated by Django 4.1 on 2024-10-31 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0105_remove_executado_documento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terceirointeressado',
            options={'verbose_name': 'Terceiros Interessados', 'verbose_name_plural': 'Terceiros Interessados'},
        ),
    ]
