# Generated by Django 4.1 on 2024-11-01 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0106_alter_terceirointeressado_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bem',
            name='depositario',
            field=models.TextField(blank=True, verbose_name='Depositário'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='fls_divida',
            field=models.PositiveIntegerField(blank=True, help_text='Número da página do <b>PDF</b> onde o valor da dívida foi encontrado', null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Fls. da Dívida'),
        ),
    ]
