# Generated by Django 4.1 on 2024-11-01 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0107_bem_depositario_alter_processo_fls_divida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='depositario',
        ),
    ]
