# Generated by Django 4.1 on 2024-11-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracao_pdf', '0108_remove_processo_depositario'),
    ]

    operations = [
        migrations.AddField(
            model_name='bem',
            name='data_avaliacao_atualizada',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Avaliação atualizada'),
        ),
        migrations.AddField(
            model_name='bem',
            name='valor_atualizado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Avaliação atualizada'),
        ),
    ]
